package main

import (
	"flag"
	"io"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
	"github.com/youpy/go-wav"
)

func main() {
	//
	line := charts.NewLine()
	// set some global options like Title/Legend/ToolTip or anything else
	line.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	// Put data into instance

	infile_path := flag.String("./test.wav", "./test.wav", "./test.wav")
	flag.Parse()

	file, _ := os.Open(*infile_path)
	reader := wav.NewReader(file)

	defer file.Close()
	items := make([]opts.LineData, 0)
	asix := make([]string, 0)
	for {
		samples, err := reader.ReadSamples()
		if err == io.EOF {
			break
		}

		for _, sample := range samples {
			items = append(items, opts.LineData{Value: reader.IntValue(sample, 0)})
		}
	}

	line.SetXAxis(asix).
		AddSeries("Category A", items)
	f, _ := os.Create("bar.html")
	line.Render(f)
}
